### ISSUE TITLE
xmlns attribute added to the root element is shown on its child elements

### ISSUE THREAD

**Issue by lazorkon** [oozcitak/xmlbuilder2#1]
**Describe the bug**
`xmlns` attribute added to the root element is shown on its child elements.
Attributes with other names are shown correctly.

NOTE: Problem appears when attributes are added via `att` method:
`.att({ xmlns: 'http://example.com', x: 0 })`

There is no problem when attributes are added via `ele` method:
`.ele('SomeRootTag', { xmlns: 'http://example.com', x: 0 })`

**To Reproduce**
```js
const builder = require('xmlbuilder2');

const xml = builder.create()
.dec({ version: '1.0', encoding: 'UTF-8', })
.ele('SomeRootTag')
.att({ xmlns: 'http://example.com', x: 0 })

.ele('foo')
.att({ a: 'A1', x: 1 })
.ele('subFoo')
.att({ a: 'A2', x: 1.1 })
.up()
.up()

.ele('bar')
.att({ b: 'B', x: 2 })

console.log(xml.end({ prettyPrint: true }));
```
Actual output - `xmlns` attribute on second elements
```xml
<?xml version="1.0" encoding="UTF-8"?>
<SomeRootTag x="0">
  <foo xmlns="http://example.com" a="A1" x="1">
    <subFoo a="A2" x="1.1"/>
  </foo>
  <bar xmlns="http://example.com" b="B" x="2"/>
</SomeRootTag>
```

**Expected behavior**
Expected output - `xmlns` attribute on root element
```xml
<?xml version="1.0" encoding="UTF-8"?>
<SomeRootTag xmlns="http://example.com" x="0">
  <foo a="A1" x="1">
    <subFoo a="A2" x="1.1"/>
  </foo>
  <bar b="B" x="2"/>
</SomeRootTag>
```

**Version:**
 - node.js: [e.g. 8.16.2]
 - xmlbuilder2 [e.g. 1.1.1]

**Additional context**
Previous version of `xmlbuilder` `13.0.2` works correctly - (`xmlns` attribute on root element)

**Comment by oozcitak** [comment]
Thank you, I'm looking into it.
