### ISSUE TITLE
Encode as UTF-16

### ISSUE THREAD

**Issue by AdamKearn** [oozcitak/xmlbuilder2#11]
**Describe the bug**
I am using this NPM package to guild an XML file that will be imported into Windows Task Scheduler. After creating the XML object using your package I then write it to a file using `fs.writeFileSync` however when I try and import the file I get errors saying `"The format of the task is not valid. The following error was reported (1,2)::ERROR: one root element."`  So I put the file into a diff checker to see if I had mistyped anything and it looks like it is encoding `<?xml` as UTF-8 instead of UTF-16.
To the eye, I can't tell the original XML file and the one created by `xmlbuilder` apart,  its just the diff-checker that is picking it up.

I was wondering if there is a way to forcefully set the encoding on the XML object???

**To Reproduce**
Here is my code  (I have slimed it down a bit so it wouldn't make this post extremely long):
```
const { create } = require('xmlbuilder2');
const fs = require('fs');

const root = create({ version: '1.0', encoding: 'UTF-16' })
  .ele('Task', { version: '1.4', xmlns: 'http://schemas.microsoft.com/windows/2004/02/mit/task' })
    ....
    .ele('Settings')
      .ele('MultipleInstancesPolicy').txt('IgnoreNew').up()
      .ele('DisallowStartIfOnBatteries').txt('false').up()
      .ele('StopIfGoingOnBatteries').txt('true').up()
    ....
  .up();

// convert the XML tree to string
const xml = root.end({ prettyPrint: true });
console.log(xml);

// Append the object to a .xml file...
fs.writeFileSync('C:\\log\\nodejs_test_xml.xml', xml, { encoding:'utf16le', flag:'w' });
```

So I just need to encode the XML as UTF-16... Is this posable ??? or am I missing something obvious?

Many thanks.

**Version:**
 - node.js: v12.16.1
 - xmlbuilder2 6.10.2

**Comment by oozcitak** [comment]
Maybe you need to write the Utf-16le BOM? Can you try:
```js
fs.writeFileSync('C:\\log\\nodejs_test_xml.xml', '\ufeff' + xml, { encoding:'utf16le', flag:'w' });
```

**Comment by AdamKearn** [comment]
@oozcitak  Yep that worked like a charm.
Thanks so much.  I appreciate what you are doing with this project.
