### ISSUE TITLE
& written instead of &amp;

### ISSUE THREAD

**Issue by HenkBoxma** [oozcitak/xmlbuilder2#110]
**Describe the bug**

When I export the following string to XML:

`Hello & world today; or tomorrow`

The XML that I get is:

`<text>Hello & world today; or tomorrow</text>`

This is invalid, because the `&` must be encoded as `&amp;`

**To Reproduce**
Export the string `Hello & world today; or tomorrow` to XML.

**Expected behavior**
Expected value: `<text>Hello &amp; world today; or tomorrow</text`

**Version:**
 - node.js: [14.17.4]
 - xmlbuilder2 [3.0.2]

**Additional context**
I suspect that the root cause is that the parser has a regular expression that assumes that all in between the `&` and `;` are treated as an entity. 
In the example above, if you'd remove the semicolon, it will export

**Comment by Laurianti** [comment]
I think it's similar issue:
https://github.com/oozcitak/xmlbuilder2/issues/109

**Comment by llamadeus** [comment]
Any news on this?
