### ISSUE TITLE
XML to JSON, preserve whitespace option

### ISSUE THREAD

**Issue by cokosharp** [oozcitak/xmlbuilder2#122]
### Discussed in https://github.com/oozcitak/xmlbuilder2/discussions/121

<div type='discussions-op-text'>

<sup>Originally posted by **cokosharp** March  9, 2022</sup>
Hello, I couldn't find any option to preserve whitespace for doc.end or convert functions, so I thought I'd try here.

In my xmlString, there's a property containing only whitespace values.
XML:
`<ValueWithBlankSpaces>                                                  </ValueWithBlankSpaces> `

When I convert it to JSON using doc.end() or convert(), the value becomes an empty object.
const doc = create(xmlString);
const jsonString = doc.end({ format: "json" });

JSON:
`"ValueWithBlankSpaces": {}`

Is there an option I can use to preserve the whitespace(s)?</div>

**Comment by oozcitak** [comment]
Fixed by #101
