### ISSUE TITLE
TS expose node interface

### ISSUE THREAD

**Issue by StefanSafeguard** [oozcitak/xmlbuilder2#153]
**Is your feature request related to a problem? Please describe.**
I'm using xmlbuilder2 in a node application for a SAML implementation, the Node implementation used by xmlbuilder2 differs from the available Node interface accessible through the dom types so it results in a type issue. 

**Describe the solution you'd like**
It would be helpful if the Node interface is exposed for use in node applications.

**Describe alternatives you've considered**
I've considered casting, but that's an ugly mess I'd like to avoid since casting is prone to lead to errors.

**Additional context**

**Comment by asportnoy** [comment]
Not ideal, but you can use `ReturnType<>` on the `create` function (or one of the other ones) to get the type. Better than nothing though.

**Comment by universalhandle** [comment]
@StefanSafeguard, I'm closing this issue as I believe it was addressed (though not in exactly the way you requested) in [v3.1.1](https://github.com/oozcitak/xmlbuilder2/releases/tag/v3.1.1). Please reopen with a code snippet and/or more information if something further is required.
