### ISSUE TITLE
Latest tagged version omits recent updates

### ISSUE THREAD

**Issue by ChimeraCoder** [oozcitak/xmlbuilder2#164]
At the moment, the latest tagged version is 3.0.2, both on npm and on Github, dated August 2021. There have been a number of changes merged to master since then, including some bug fixes. Are there plans to release a minor/patch version bump so that users can pick up these changes when downloading from the npm registry?

**Comment by universalhandle** [comment]
Yes, apologies for the delay. I've just joined as a co-maintainer and will be able to do this early next week. Cheers!

**Comment by universalhandle** [comment]
Closed with [v3.1.0](https://github.com/oozcitak/xmlbuilder2/releases/tag/v3.1.0).

**Comment by ChimeraCoder** [comment]
Thanks!
