### ISSUE TITLE
move exsiting dependnecy `@types/node` from run-time to build-time

### ISSUE THREAD

**Issue by jkowalleck** [oozcitak/xmlbuilder2#165]
**Describe the bug**

the package currently requires `@types/node` for RUNTIME. this appeases to be an error. 

therefore, every productive installation of this package will install `@types/node` -- for what reason?!
Caused by https://github.com/oozcitak/xmlbuilder2/blob/9443dbfe0f18471903c0a7e08912a1c0221fc506/package.json#L33

**To Reproduce**
install this package without any dev nor optional dependencies, as a downstream dependency,
and you will find `@types/node` installed

**Expected behavior**
no dev-dependencies are installed downstream.

**Version:**
 - node.js: *
 - xmlbuilder2: <= 3.1.0

**Additional context**

`@types/node` is a dev dependency, that provides type hints digested by developer tools and TypeScript, on build-time.
It is not required on run-time.

**Comment by jkowalleck** [comment]
Possibly related: #153

**Comment by universalhandle** [comment]
Hi, @jkowalleck. Thanks for the issue and pull request. I'm inclined to agree that `@types` packages need only be dev dependencies. I'm going to revisit the threads you linked just to be thorough, but I expect I'll be merging and shipping it.
