### ISSUE TITLE
Reconsider allowing XML file creation in chunks

### ISSUE THREAD

**Issue by vanstinator** [oozcitak/xmlbuilder2#2]
**Is your feature request related to a problem? Please describe.**

At my company we're using `xmlbuilder` to create an XML file from a database stream using `begin with callback`. The dataset won't fit into memory and requires the ability to either stream to a file or write the file in chunks.

**Describe the solution you'd like**

We'd like to see `xmlbuilder2` retain the ability to write to a file in chunks

**Describe alternatives you've considered**

We could probably use the `xmlbuilder2` to generate chunks of xml that we write to a file ourselves. But that's a lot of potential boilerplate code that would fit better inside this library.

**Comment by oozcitak** [comment]
Fixed. Related commits: a94d1054d3a62dd53da732d8e415fe2dddb86491, ae4243d7e7a9213cc8136faba1634ba0344e5296 and 0b4da1eddb8eccc46bd1f802887e9752a5d74db4

**Comment by ainthek** [comment]
Please and docs and samples for this Streaming Writing ? Thanx

**Comment by oozcitak** [comment]
It's already in the docs: https://oozcitak.github.io/xmlbuilder2/builder-functions-with-callbacks.html#createCB and there are more at the bottom of the sidebar.

Let me know if anything is missing.

**Comment by dobromyslov** [comment]
Thank you for the streaming API.

Please add docs to the main readme file. I've been looking for the streaming way at the NPM and GitHub repo first of all. And at last found this issue leading to the docs.

**Comment by oozcitak** [comment]
There is already a link to docs at the bottom of readme.

**Comment by manelio** [comment]
Maybe I'm missing something, but I can't find out how to create a huge XML document by using the callback API together with fragment/import/create functions.

Let me explain what I mean:

There's a common use case: generation of a feeds. Large files with large amounts of posts, ecommerce products or whatever.

I prefer creating single items by using the create function. Something like this:

```
const xml = createCB({
  data: (text) => process.stdout.write(text),
});

const item = create({
  item: {
    sku: '001',
    name: 'Product name',
  }
});

xml.dec().ele('rss').import(item);
```

But there's no `import` function in elements created with createCB API.

Is there any way to achieve something like this?

**Comment by oozcitak** [comment]
> Is there any way to achieve something like this?

No, I'll add this.
