### ISSUE TITLE
Number 0 is omitted when converting object to xml

### ISSUE THREAD

**Issue by linkeo** [oozcitak/xmlbuilder2#21]
**Describe the bug**
When converting object to xml, it's not expected to convert number `0` into empty content.

**To Reproduce**

```js
const { create } = require('xmlbuilder2');

const xml = create().ele({ value: 0 }).end()
```

will produce

```xml
<?xml version="1.0"?><root><value/></root>
```

**Expected behavior**

It should be

```xml
<?xml version="1.0"?><root><value>0</value></root>
```

**Version:**
 - node.js: [12.13.0]
 - xmlbuilder2 [2.1.2]

**Additional context**

**Comment by linkeo** [comment]
@oozcitak Is it ok to change this condtion to `else if (value != null)`

https://github.com/oozcitak/xmlbuilder2/blob/3a30fbedebe60642c5047b8fad0739e9d3b2de97/src/builder/XMLBuilderImpl.ts#L170-L172

**Comment by oozcitak** [comment]
Yes that should do it. Would you like to send a PR?

**Comment by linkeo** [comment]
@oozcitak ok, i will send it soon
