### ISSUE TITLE
\r encoding in element txt

### ISSUE THREAD

**Issue by neilcampbell** [oozcitak/xmlbuilder2#24]
**Describe the bug**
I am building some xml which sometimes has \r\n characters in the text, which results in what feels like some inconsistent encoding behaviour. It appears to be due to https://github.com/oozcitak/xmlbuilder2/blob/master/src/writers/BaseWriter.ts#L937

I have tried removing the above line and no tests break, so I'm trying to work out why it exists? Happy to submit a PR if you think it can be removed.

**To Reproduce**
```
import { create } from 'xmlbuilder2';

const root = create().ele('parent', {
  text: 'Hello \r\n'
});
root
  .ele('child')
  .txt('Line 1\r\nLine 2\r\nLine 3');

console.log(root.end({
  prettyPrint: true,
  headless: true,
  newline: '\r\n',
  noDoubleEncoding: true,
}));
```

Actual Output
```
<parent text="Hello &#xD;&#xA;">
  <child>Line 1&#xD;
Line 2&#xD;
Line 3</child>
</parent>
```

**Expected behavior**
When I set the line endings to \r\n, I'd expect both the \r and \n to not be encoded within the element text. Currently only the \n is not being encoded.

Expected Output
```
<parent text="Hello &#xD;&#xA;">
  <child>Line 1
Line 2
Line 3</child>
</parent>
```

**Version:**
 - node.js: [12.6.0]
 - xmlbuilder2 [2.1.4]

**Comment by oozcitak** [comment]
> I have tried removing the above line and no tests break, so I'm trying to work out why it exists? Happy to submit a PR if you think it can be removed.

They should probably be removed (there is also a similar check for attribute values). But let me check the spec tonight and get back to you.

**Comment by neilcampbell** [comment]
@oozcitak Awesome, thanks heaps!

**Comment by neilcampbell** [comment]
@oozcitak Just looking at https://github.com/oozcitak/xmlbuilder2/commit/87adb725509fa2edb85787fd2f340de0a0e5d808. Is it valid to have an attribute value containing \r or \n chars without them being encoded?
