### ISSUE TITLE
Support browsers

### ISSUE THREAD

**Issue by oozcitak** [oozcitak/xmlbuilder2#28]
As `xmlbuilder2` can also be used in the browser, it should support major browsers. See: https://github.com/oozcitak/dom/issues/2

**Comment by oozcitak** [comment]
This should be fixed with version `2.1.6`. I could only add a few browser tests at the moment; so please report any issues you run into. Also in order to use the library on IE11, you need to polyfill `Promise` and `Reflect`, e.g.:

```html
<script type = "text/javascript" src = "es6-proxy-polyfill.js"></script>
<script type = "text/javascript" src = "reflect.js"></script>
<script type = "text/javascript" src = "xmlbuilder2.min.js"></script>
```

**Comment by Nunomcg** [comment]
Thank you! 
xmlbuilder2 `2.1.6` is working fine for me on IE11.
The polyfills were not necessary  on my `Angular 9` project.

**Comment by christopherthurnher** [comment]
I updated my Angular 9 project to xmlbuilder2 `2.1.6`, then I got the error:

`ERROR ReferenceError: "Proxy" ist undefiniert`

So I tried to polyfill `Proxy` and `Reflect` as you mentioned above. I added the following lines to my polyfill.ts

```
import 'es6-proxy-polyfill/dist/es6-proxy-polyfill'
import 'harmony-reflect/reflect'
```
Now I get an Error in IE11 when starting the Application:

`"global" ist undefiniert` (global is not defined)
