### ISSUE TITLE
How can I omit the <?xml version="1.0"?> header?

### ISSUE THREAD

**Issue by Doc999tor** [oozcitak/xmlbuilder2#3]
I want to build only the body with root xml tag but without the necessary `<?xml version="1.0"?>` header  
How can I do it declaratively?

**Comment by oozcitak** [comment]
You use the `headless` option when serializing:

``` js
const { create } = require('xmlbuilder2');

const root = create({ version: '1.0' })
  .ele('root', { att: 'val' })
    .ele('foo')
    .up()
  .up();

const xml = root.end({ headless: true, prettyPrint: true });
console.log(xml);
```

``` xml
<root att="val">
  <foo/>
</root>
```
See: https://github.com/oozcitak/xmlbuilder2/wiki/Serialization#serialization-settings

**Comment by Doc999tor** [comment]
Oh, great  
`headless: true` - I totally missed it  
Thanks
