### ISSUE TITLE
Conversion from XML to JSON array inconsistency

### ISSUE THREAD

**Issue by eugenevd** [oozcitak/xmlbuilder2#30]
**Describe the bug**
Given XML with multiple rows:

```<export>
    <data>
        <row id="0">
            <TYPE>X</TYPE>
            <ID>123</ID>            
        </row>
        <row id="1">
            <TYPE>Y</TYPE>
            <ID>321</ID>           
        </row>
    </data>   
```

produces JSON with row as array.

vs XML with a single row:

```<export>
    <data>
        <row id="0">
            <TYPE>X</TYPE>
            <ID>123</ID>            
        </row>
    </data>   
```

produced JSON with row not as an array.

**To Reproduce**

```const chai = require('chai');
const expect = chai.expect;
const { convert } = require('xmlbuilder2');
describe('Test XML to JSON arrays', function ()
{
    it('Multiple items in XML should result in JSON array', async function()
    {
        const XMLmulti = '<export><data><row id="0"><TYPE>X</TYPE><ID>123</ID></row><row id="1"><TYPE>Y</TYPE><ID>321</ID></row></data></export>';
        let JSONmulti = convert(XMLmulti, { format: "object" });
        expect(JSONmulti.export.data.row.length).to.equal(2);
    });
    it('Single item in XML should result in JSON array', async function()
    {
        const XMLsingle = '<export><data><row id="0"><TYPE>X</TYPE><ID>123</ID></row></data></export>';
        let JSONsingle = convert(XMLsingle, { format: "object" });
        expect(JSONsingle.export.data.row.length).to.equal(1);
    });
});
```

**Expected behavior**
Result:
`{
  "export": {
    "data": {
      "row": {
        "@id": "0",
        "TYPE": "X",
        "ID": "123"
      }
    }
  }
}`
Expected:
`{
  "export": {
    "data": {
      "row": [{
        "@id": "0",
        "TYPE": "X",
        "ID": "123"
      }]
    }
  }
}`

**Version:**
 - node.js: [12.18.0]
 - xmlbuilder2 [2.1.6]

**Comment by oozcitak** [comment]
This would force elements with single child nodes to always create arrays. I don't think we want this:

```js
{
  root: [
    {
      child: [
        {
          grandchild: [
            {
              "text"
            }
          ]
        }
      ]
    }
  ]
}
```
Your expected output should also be:
```js
Expected:
{ "export": [{ "data": [{ "row": [{ "@id": "0", "TYPE": "X", "ID": "123" }] }] }] }
```
as `"row"`, `"data"` and `"export"` are all elements with single child nodes.

Is there a reason you want this feature, or is it just for consistency's sake?

**Comment by IamRaduB** [comment]
Encountering the same issue. It would be great to be able to pass a set of xpaths to the converter telling it: these nodes should be arrays.

**Comment by oozcitak** [comment]
> pass a set of xpaths to the converter

If I am understanding this correctly, you want to determine which element nodes should have their contents to be always grouped into an array. I am guessing you are post-processing the resulting JS object. Maybe it would be better to allow customizing the converter; so you can tweak the output as you require.  Can you describe the use case a bit?

**Comment by gpyshenko** [comment]
I support this proposal, it very useful. It is convenient to get the expected result.

**Comment by eugenevd** [comment]
For me it's about consistency. I retrieve XML data from a SOAP service. After converting to JSON, I process it. The code would be much simpler if I knew I'll always have an array where expected (array with 0,1 or more elements).

**Comment by leog** [comment]
I too bumped with this requirement @oozcitak. Maybe using the element custom parser to enforce array treatment for selected element names? 🤔

**Comment by oozcitak** [comment]
@leog I started working on custom serializers. You can track the progress at #47
