### ISSUE TITLE
Change node  text  tag content

### ISSUE THREAD

**Issue by joweste** [oozcitak/xmlbuilder2#34]
Hi,
I have created the next xml with this package.
How, I have to fix the content of the "hash" tag.
How could I find and replace the content of that tag?
I´d like to change to:
`<ans:hash>09772da3dd9faf7fa8d6ef7374de501c</ans:hash>`

My xml:
```
<?xml version="1.0" encoding="ISO-8859-1"?>
<ans:mensagemTISS xmlns:ans="http://www.ans.gov.br/padroes/tiss/schemas" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ans.gov.br/padroes/tiss/schemas http://www.ans.gov.br/padroes/tiss/schemas/tissV3_02_00.xsd">
  .....
  .....
  <ans:epilogo>
    <ans:hash>07662da3dd9faf7fa8d6ef2044de701c</ans:hash>
  </ans:epilogo>
</ans:mensagemTISS>

```

**Comment by oozcitak** [comment]
İt depends on the structure of your document. You can use the [traversal functions](https://oozcitak.github.io/xmlbuilder2/traversal-functions.html) or [find](https://oozcitak.github.io/xmlbuilder2/collection-functions.html#find) or [xpath](https://oozcitak.github.io/xmlbuilder2/using-with-external-libraries.html#xpath) to find a specific node then you can change the node content with the DOM data property.

**Comment by joweste** [comment]
> İt depends on the structure of your document. You can use the [traversal functions](https://oozcitak.github.io/xmlbuilder2/traversal-functions.html) or [find](https://oozcitak.github.io/xmlbuilder2/collection-functions.html#find) or [xpath](https://oozcitak.github.io/xmlbuilder2/using-with-external-libraries.html#xpath) to find a specific node then you can change the node content with the DOM data property.

Thank, I solved it with your help
