### ISSUE TITLE
Verbose parameter work incorrect

### ISSUE THREAD

**Issue by gpyshenko** [oozcitak/xmlbuilder2#38]
Input XML
```
<resources></resources>
```
I used convert({encoding: 'UTF-8', convert: {text: 'value'}}, input, {format: 'object', group: true, verbose: true})

Expect output
```
{ resources: [] }
```

Output
```
{ resources: [{}] }
```

**Comment by oozcitak** [comment]
`resources: []` means there are zero `resources` nodes. `resources: [{}]` mean there is one `resources` node with empty content. The output is correct in this case. From the [docs](https://oozcitak.github.io/xmlbuilder2/object-conversion.html):
> If the object value is an array, each array item will be converted into a child node. In that case, name of the child nodes will be the object key.
