### ISSUE TITLE
Can't import type in Nestjs project

### ISSUE THREAD

**Issue by vschoener** [oozcitak/xmlbuilder2#4]
**Describe the bug**
I tried to import the type from this package and I can't get the type properly.
So I don't know if it's a tsconfig issue from my side or yours, but til now, it's the first time I get this unresolved type.

Any idea?

![image](https://user-images.githubusercontent.com/1213200/75627814-df409480-5bd3-11ea-93e1-03323e242e08.png)

**To Reproduce**
From an existing TS project:
```
import { create }  from 'xmlbuilder2';
```

Try to get the autocomplete inside the brackets and see if you get definitions.

**Expected behavior**
Having my IDE giving the available types

**Version:**
 - node.js: 12.13.0
 - xmlbuilder2: 1.4.1

**Additional context**

**Comment by oozcitak** [comment]
I tested importing `xmlbuilder2 1.4.1` in an empty folder and I get VS Code intellisense fine:

![test-import](https://user-images.githubusercontent.com/188041/75663516-fccc3780-5c81-11ea-8817-f10a8094751b.png)

I then tested importing `xmlbuilder2 1.4.1` into the NestJS starter project and it also works:

![test-nestjs](https://user-images.githubusercontent.com/188041/75664523-a3fd9e80-5c83-11ea-94eb-b2895758cc4e.png)

I think this is something on your end.

**Comment by vschoener** [comment]
Thanks @oozcitak for your time.

Damn, no idea why it doesn't work. I use Webstorm but it should not make this difference.
The compilation and the app was working, so it's was good and as I can put the Type in my service, I had the completion from there, but not in the provider I tried to created.

I'll try again, reinstalling the project and restarting IDE.

**Comment by vschoener** [comment]
So yeah I confirmed from another computer, with fresh install of the project I don't get the completion with webstorm :( 

I know there are sometimes differences between vscode and webstorm to get information, I'll dig a bit see if I can find something

**Comment by vschoener** [comment]
Maybe it's due to the fact that other project put the index.d.ts in the root of the package and have also  tsconfig giving the location of the other definition?

Just saying it might be related, see winston project https://github.com/winstonjs/winston

**Comment by oozcitak** [comment]
I confirmed that there is no intellisense with WebStorm.

> Maybe it's due to the fact that other project put the index.d.ts in the root of the package and have also tsconfig giving the location of the other definition?

This appears to be the case, I'm adding an explicit `types` path to `package.json`. Thank you for investigating.
