### ISSUE TITLE
invalidCharReplacement does not work in a convert scenario

### ISSUE THREAD

**Issue by leoglobant** [oozcitak/xmlbuilder2#48]
**Describe the bug**
When converting an XML to JSON, I want to be able to specify the replacements for invalid chars using the builder option `invalidCharReplacement`.

**To Reproduce**
```javascript
const xml = fs.readFileSync("./test.xml", "utf-8");
const obj = convert({ 
  invalidCharReplacement: ''
}, xml, { 
  format: 'object'
});
fs.writeFileSync("./test.json", JSON.stringify(obj));
```

**Expected behavior**
When any invalid char is detected in the converted XML, it should be replaced with the specified string.

**Version:**
 - node.js: [12.18.0]
 - xmlbuilder2 [2.3.1]

**Additional context**
N/A

**Comment by oozcitak** [comment]
Can you post the contents of `test.xml` or similar to reproduce?

**Comment by leog** [comment]
Sorry @oozcitak, the whole bug appeared not exactly when having invalid chars in the xml but when having an invalid char put purposely in the att convert option. Wrongly assumed it behaved the same for the content of the xml.

**Comment by leoglobant** [comment]
Sorry @oozcitak, the whole bug appeared not exactly when having invalid chars in the xml but when having an invalid char put purposely in the att convert option. Wrongly assumed it behaved the same for the content of the xml.

**Comment by oozcitak** [comment]
@leoglobant Closing this then.
