### ISSUE TITLE
Is there any way I can append urls to pre existing urlset in a file created before.

### ISSUE THREAD

**Issue by jawadakram20** [oozcitak/xmlbuilder2#50]
**Is your feature request related to a problem? Please describe.**
I want to update the sitemap.xml file and keep everything inside a single URL set. It is being created on build time. so at one time, it is created and then needs to append more URLs inside it. But the docs have the only method to create a URL set and then add elements. How can I read the file pick pre-existing URL set and append more URLs?

**Comment by oozcitak** [comment]
Please fill in the issue template. Your question is not clear to me from the title alone.

**Comment by jawadakram20** [comment]
@oozcitak updated please check.

**Comment by oozcitak** [comment]
You can use the [`create`](https://oozcitak.github.io/xmlbuilder2/builder-functions.html#create) function to read an existing XML file:

```js
const { readFileSync, writeFileSync } = require('fs');
const { create } = require('xmlbuilder2');

let sitemapData = readFileSync('/path/to/sitemap.xml');
const doc = create(sitemapData); // parse sitemap
const root = doc.root(); // root element node, i.e. <urlset>
root.ele('url') // append a new <url> element
  .ele('loc').txt('http://www.example.com').up()
  .ele('lastmod').txt('2020-01-01').up()
.up();
sitemapData = doc.end(); // update sitemap
writeFileSync('/path/to/sitemap.xml', sitemapData);
```
