### ISSUE TITLE
 Class 'XMLBuilderCBImpl' incorrectly implements interface 'XMLBuilderCB'

### ISSUE THREAD

**Issue by nlsnightmare** [oozcitak/xmlbuilder2#52]
**Describe the bug**
When i try to compile my code using tsc i get the following compile error. When i run the code with ts-node, it runs fine.

**To Reproduce**
Use the xml builder

**Expected behavior**
The code compiles

**Version:**
 - typescript 3.3.3333
 - xmlbuilder2 2.3.1

**Comment by oozcitak** [comment]
I can't reproduce this. Can you post your code?

**Comment by nlsnightmare** [comment]
I created a new project, just to make a sanity check. I followed the following steps: 
```bash
mkdir xmlbuilder2-test && cd $_
mkdir src
tsc --init
npm init -y
npm install xmlbuilder2
```

After that, i added the following code to `src/index.ts`: 
```typescript
import { create } from "xmlbuilder2";
import { XMLBuilder } from "xmlbuilder2/lib/interfaces";
function main() {
    const builder: XMLBuilder = create()
        .ele('some-element');

    console.log('i created the xml', builder.end({ prettyPrint: true }))
}

main()
```

After that, I run `tsc` in the project root, and... it worked! So I did some digging. Turns out, the tsconfig.json which was autogenerated containg the flag `skipLibCheck: true` on by default. When I added the flag to my original project, it compiled!

My problem is practically solved, however I'll leave the issue open in case you want to dig deeper.

**Comment by oozcitak** [comment]
Thank you for investigating. I am including `@types/node` in `dependencies` as the library exports some `node` types.
