### ISSUE TITLE
Automatic escaping of characters applied unnecessarily

### ISSUE THREAD

**Issue by leoglobant** [oozcitak/xmlbuilder2#58]
**Describe the bug**
When a node text contains the character `&` it automatically becomes escaped with `&amp;`, due to [this line of code](https://github.com/oozcitak/xmlbuilder2/blob/master/src/writers/BaseWriter.ts#L942). In my case, the text already comes escaped, so `&amp;` becomes `&amp;amp;`.

**To Reproduce**
Have an XML with escaped text inside. Convert it to object. The result object has the double-escaped text.

**Expected behavior**
There should be a mechanism to detect the chars are already escaped before applying the automatic escaping.

**Version:**
 - node.js: 12.18.0
 - xmlbuilder2 2.4.0

**Additional context**
N/A

**Comment by oozcitak** [comment]
Did you use the `noDoubleEncoding` flag?

https://oozcitak.github.io/xmlbuilder2/serialization.html#serialization-settings

**Comment by Doc999tor** [comment]
@leoglobant @oozcitak 
I'm facing this issue but I can't make it working 
```
var xml = require('xmlbuilder2')
xml.create({message: '/foo?param1=900&param2=1000'}).toString({ prettyPrint: true, noDoubleEncoding: true })

 '<?xml version="1.0"?>\n' +
  '<message>/foo?param1=900&amp;param2=1000</message>'
```
