### ISSUE TITLE
Support `noValidation` option from xmlbuilder1

### ISSUE THREAD

**Issue by kellyselden** [oozcitak/xmlbuilder2#59]
I'm transforming an XML (JUnit) file, and it would be nice if the attributes matched. Right now this is what happens:

input:

```xml
<testsuite>
  <testcase name="foo > bar"/>
</testsuite>
```

output:

```xml
<testsuite>
  <testcase name="foo &gt; bar">
    <failure/>
  </testcase>
</testsuite>
```

I understand that the output is more correct, but it would be nice to match the option from xmlbuilder1 `noValidation` https://github.com/oozcitak/xmlbuilder-js/blob/e4ddc615b3668c63c63e627fb1b6fc078d586ba3/src/XMLStringifier.coffee#L164.

**Comment by oozcitak** [comment]
The library applies the [XMLSerializer](https://www.w3.org/TR/DOM-Parsing/#dfn-concept-serialize-attr-value) interface as is. I want to keep the default implementation as close to the specs as possible. The option you require will be possible with custom serializers. Please watch the related issue: #47.
