### ISSUE TITLE
toString applied on DOM node?

### ISSUE THREAD

**Issue by phdggg** [oozcitak/xmlbuilder2#62]
I got the DOM node by using https://oozcitak.github.io/xmlbuilder2/other-functions.html#node.
After several operations using DOM functions (like getElementsByTagName, etc.) Now for a node, I only have the DOM mode.
How should I string convert that node to a string?

**Comment by oozcitak** [comment]
If the dome node was created by xmlbuilder2 you can convert it back with the [builder](https://oozcitak.github.io/xmlbuilder2/builder-functions.html#builder) function.
