### ISSUE TITLE
Expose tag name encoding

### ISSUE THREAD

**Issue by josh-hemphill** [oozcitak/xmlbuilder2#65]
**Is your feature request related to a problem? Please describe.**
When implementing your own element parser, all XML illegal characters have to be manually escaped. 

**Describe the solution you'd like**
Some way to reimplement this behavior in custom parser functions.

**Describe alternatives you've considered**
Importing the dom or utils library that xmlbuilder2 uses, but I was not able to find what function xmlbuilder2 is using internally.

**Comment by oozcitak** [comment]
If you are asking about the character production in the [XML spec](https://www.w3.org/TR/xml/#charsets), I can expose the internal function to the parser.
