### ISSUE TITLE
 Xpath examples in documentation

### ISSUE THREAD

**Issue by rivaros** [oozcitak/xmlbuilder2#67]
Hi,

Could you provide more information how to use xpath in xmlbuilder2.
For example in code below:

```
import { create } from "xmlbuilder2";
import { select } from "xpath";

    const obj = {
        prop1: {
            prop2: 'Prop2Value',
            prop3: 'Prop3Value'
        }
    }

    let doc = create({ encoding: "UTF-8" }, obj);

    let selected = select('//prop3', doc.node);

```

am getting error `Argument of type 'import("/project1/node_modules/@oozcitak/dom/lib/dom/interfaces").Node' is not assignable to parameter of type 'Node'.
  Property 'namespaceURI' is missing in type 'import("/project1/node_modules/@oozcitak/dom/lib/dom/interfaces").Node' but required in type 'Node'.ts(2345)
lib.dom.d.ts(10799, 14): 'namespaceURI' is declared here.`

**Comment by oozcitak** [comment]
I added a note to the documentation. The baseline is you need to cast between types (or cast `as any`) since types between `XMLBuilder2` and `xpath` are different.
