### ISSUE TITLE
Previous invalid decode of XML escape sequences not fixed for 2.4.0

### ISSUE THREAD

**Issue by crolex** [oozcitak/xmlbuilder2#68]
This previous defect does not seem to be fixed or has retured. I added the `noDoubleEncoding:true `to the convert() options using version 2.4.0

To Reproduce defect 1:
```
const xmlbuilder2 = require("xmlbuilder2");
const assert = require("assert");
const originalXML = `<?xml version="1.0"?><example>&lt;p&gt;Hello&lt;/p&gt;</example>`;
console.log("originalXML:", originalXML);
const objectXML = xmlbuilder2.convert(originalXML, { format: "object", noDoubleEncoding: true });
assert.strictEqual( objectXML, {example:'<p>Hello</p>'} );
```
Result:
```
AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

  {
-   example: '&lt;p&gt;Hello&lt;/p&gt;'
+   example: '<p>Hello</p>'
  }
```

The decoded XML which contains valid &lt; and &gt; escapes does not result in the expected output as reported by @leafac. 
The addition of the `noDoubleEncoding:true` option also does not correct the round trip XML->JS->XML.

To reproduce defect 2:
```
const xmlbuilder2 = require("xmlbuilder2");
const assert = require("assert");
const originalXML = `<?xml version="1.0"?><example>&lt;p&gt;Hello&lt;/p&gt;</example>`;
console.log("originalXML:", originalXML);
const objectXML = xmlbuilder2.convert(originalXML, { format: "object", noDoubleEncoding: true });
console.log("objectXML:", JSON.stringify(objectXML, null, 2));
const recreatedXML = xmlbuilder2.convert(objectXML, { format: "xml" });
console.log("recreatedXML:", recreatedXML);
assert.strictEqual(recreatedXML, originalXML);
```
Result:
```
AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

- '<?xml version="1.0"?><example>&amp;lt;p&amp;gt;Hello&amp;lt;/p&amp;gt;</example>'
+ '<?xml version="1.0"?><example>&lt;p&gt;Hello&lt;/p&gt;</example>'
```

_Originally posted by @crolex in https://github.com/oozcitak/xmlbuilder2/issues/15#issuecomment-749291883_

**Comment by oozcitak** [comment]
@crolex You are missing the `noDoubleEncoding` flag in your second example. This line:
```js
const recreatedXML = xmlbuilder2.convert(objectXML, { format: "xml" });
```
should be:
```js
const recreatedXML = xmlbuilder2.convert(objectXML, { format: "xml", noDoubleEncoding: true });
```

**Comment by jimmythomson** [comment]
I'm seeing the same issue as @crolex using 2.4.0. The use of `noDoubleEncoding` has no impact.

**Comment by jimmythomson** [comment]
Here's a demo of the issue using the first section of code that @crolex posted: https://repl.it/@jimmythomson/xmlbuilder2-issues-68

**Comment by oozcitak** [comment]
`noDoubleEncoding` prevents re-encoding. It does not decode existing encoded entities. Please see the explanation here: https://github.com/oozcitak/xmlbuilder2/issues/73#issuecomment-778045101. What you are looking for is probably someting like underscore's [`unescape`](http://underscorejs.org/#unescape). This library doesn't have such a function.
