### ISSUE TITLE
Error When Compiling Angular 8 Source Code

### ISSUE THREAD

**Issue by EthanTuning** [oozcitak/xmlbuilder2#7]
**Description:**
Compilation error triggered when running `ng serve`. Error is very unpredictable. Some times the compiler reports the error but the application still runs and works fine. Other times the error halts compilation and execution all together.

**To Reproduce:**
Simply run `ng serve` on application.

**Expected behavior:** 
Should compile and run fine with no errors.

**Version:**
 - node.js: [10.15.1]
 - xmlbuilder2 [1.4.3]

**Additional context:**
The attached photo shows both cases after compilation. The top highlighted section is an example of the project not being compiled and not executing due to error. The bottom highlighted section shows the error being reported, yet still compiling and running just fine.

![Screenshot_1](https://user-images.githubusercontent.com/17459105/76249718-2dbbe780-6201-11ea-85b8-860463394014.png)

**Comment by oozcitak** [comment]
Your angular version?

**Comment by oozcitak** [comment]
It appears this is an angular issue. Upgrading to Angular 9 or updating TypeScript should resolve this. See: https://github.com/storybookjs/storybook/issues/9463

**Comment by EthanTuning** [comment]
Great, thanks. Will look into that.
