### ISSUE TITLE
Unable to assign attribute to nested node if already assigned higher-up

### ISSUE THREAD

**Issue by mcab** [oozcitak/xmlbuilder2#72]
**Describe the bug**
I'm trying to assign a particular attribute (`xmlns:ds`) with the same key, value pairing, which has also been previously defined on a higher-level element. It applies correctly for the node closest to the root, but not for the lower nodes nodes.

**To Reproduce**
```javascript
const { create } = require('xmlbuilder2');

function convertor(cert) {
    return {
        '@use': 'signing',
        'foobar': {
            '@xmlns:ds': 'att',
            'foobaz': {
                'foobarbaz': cert,
            }
        },
    }
}

function create_metadata(certs) {
    let final_certs = []
    for (cert in certs) {
        final_certs.push(convertor(certs[cert]))
    }

    xml = create({
        'foo': {
            '@xmlns:ds': 'att',
            'bar': {
                'baz': final_certs
            }
        }
    }).end({ prettyPrint: true })
    console.log(xml);
}

create_metadata(['cert1', 'cert2'])

```

**Expected behavior**
I expect each `foobar` to have `@xmlns:ds` as an attribute, but they do not.

The current output (2.4.0) looks like:
```xml
<?xml version="1.0"?>
<foo xmlns:ds="att">
  <bar>
    <baz use="signing">
      <foobar>
        <foobaz>
          <foobarbaz>cert1</foobarbaz>
        </foobaz>
      </foobar>
    </baz>
    <baz use="signing">
      <foobar>
        <foobaz>
          <foobarbaz>cert2</foobarbaz>
        </foobaz>
      </foobar>
    </baz>
  </bar>
</foo>
```

What I'm expecting:
```xml
<?xml version="1.0"?>
<foo xmlns:ds="att">
  <bar>
    <baz use="signing">
      <foobar xmlns:ds="att">
        <foobaz>
          <foobarbaz>cert1</foobarbaz>
        </foobaz>
      </foobar>
    </baz>
    <baz use="signing">
      <foobar xmlns:ds="att">
        <foobaz>
          <foobarbaz>cert2</foobarbaz>
        </foobaz>
      </foobar>
    </baz>
  </bar>
</foo>
```

Before passing to `create()`, the structure hints that the attribute should be set:
```javascript
[
  {
    '@use': 'signing',
    foobar: {
      '@xmlns:ds': 'att',
      foobaz: [Object]
    }
  },
  {
    '@use': 'signing',
    foobar: {
      '@xmlns:ds': 'att',
      foobaz: [Object]
    }
  }
]
```

**Version:**
 - node.js: [12.4.1]
 - xmlbuilder2 [2.4.0]

**Comment by mcab** [comment]
Ah, it seems to be https://github.com/oozcitak/xmlbuilder2/issues/20, but in reverse. 😅

**Comment by oozcitak** [comment]
This is not a bug but a feature of the serializer.

`xmlbuilder2` keeps a record of namespaces while serializing the document. It can add, modify and even remove namespace prefixes. But it preserves the _meaning_ of the document.

In your case, the parent `foo` element node declares the namespace `att` with the prefix `ds`. So, `foo` and all of its child elements has access to this namespace. Redeclaring the namespace under the child `foobar` element node is redundant as it is already declared by `foo`. If you would canonicalize both documents you would see they are identical.
