### ISSUE TITLE
Can't make noDoubleEncoding working

### ISSUE THREAD

**Issue by Doc999tor** [oozcitak/xmlbuilder2#73]
According to the [docs](https://oozcitak.github.io/xmlbuilder2/serialization.html#serialization-settings) every serializer has common `noDoubleEncoding` option to prevent unnecessarily escaping

```
var xml = require('xmlbuilder2')
xml.create({url: '/foo?param1=1&param2=2'}).toString({ noDoubleEncoding: true })
xml.create({url: '/foo?param1=1&param2=2'}).end({ format: 'xml', noDoubleEncoding: true })
```
Both return `<url>/foo?param1=900&amp;param2=1000</url>` with escaped `&` character

In [4.2.0 changelog](https://github.com/oozcitak/xmlbuilder-js/releases/tag/v4.2.0) I found that I can add `noDoubleEncoding` to the `create` method - unsuccessfully

[Related issue](https://github.com/oozcitak/xmlbuilder2/issues/58)
Version of xmlbuilder2: "^2.4.0"
What is the correct syntax for using this option?

**Comment by oozcitak** [comment]
`noDoubleEncoding` prevents re-encoding. For example:

Value | without `noDoubleEncoding` | with `noDoubleEncoding`
------ | ---- | ----
`Smith&amp;Wesson` | `Smith&amp;amp;Wesson` | `Smith&amp;Wesson`

What you are asking for is to prevent encoding all together; which is not possible.
