### ISSUE TITLE
Obj To XML conversion is getting failed for some values.

### ISSUE THREAD

**Issue by Prince-Mehmi** [oozcitak/xmlbuilder2#74]
**Describe the bug**
If i give MongoDB as value for any key it gives exception :-
Error [InvalidCharacterError]: The string contains invalid characters. Invalid XML name: 0

**To Reproduce**
In obj for which you want to do conversion to XML add any key with value as "60278a01be546405980fd18e"

**Expected behavior**
It should successfully convert Obj to XML.

**Version:**
 - node.js: [15.8.0]
 - xmlbuilder2 [2.4.0]

**Additional context**
If i add any alphabet in beginning like "a60278a01be546405980fd18e" it works successfully.
According to me issue is related to some kind of validation within following code :-
Within File - NamespaceAlgorithm.js
if (!XMLAlgorithm_1.xml_isName(qualifiedName))
        throw new DOMException_1.InvalidCharacterError("Invalid XML name: " + qualifiedName);

**Comment by oozcitak** [comment]
Xml names cannot start with numbers. This is against the Xml spec. You may try prepending an underscore before the name or a similar solution.
