### ISSUE TITLE
HierarchyRequestError: The operation would yield an incorrect node tree

### ISSUE THREAD

**Issue by daorren** [oozcitak/xmlbuilder2#79]
**Describe the bug**
when I use xmlbuilder2 to convert a xml, it throw an error: 
```
HierarchyRequestError: The operation would yield an incorrect node tree. Cannot insert a text node as a child of a document node. Node is #text
```

**To Reproduce**
just use this xml
[09.house.musicxml.zip](https://github.com/oozcitak/xmlbuilder2/files/6108157/09.house.musicxml.zip)

**Expected behavior**
no error encounting

**Version:**
 - node.js: 10.22.1
 - xmlbuilder2 2.4.0

**Additional context**
After some trial & error, I found that it's the file's encoding "UTF-8 with BOOM" cause the problem.

**Comment by daorren** [comment]
Turns out that it's not the xml string, but the file that has sth wrong
[09.house.musicxml.zip](https://github.com/oozcitak/xmlbuilder2/files/6108147/09.house.musicxml.zip)

**Comment by daorren** [comment]
I'm not sure whether it's a bug, if it's not, just notify me and I'll close this issue

**Comment by oozcitak** [comment]
I don't think it is this library's responsibility to manage BOMs. BOM markers would be best managed at the time of file I/O. Thanks for investigating the issue.

**Comment by daorren** [comment]
OK, I'm closing this issue
