### ISSUE TITLE
convert does not respect encoding

### ISSUE THREAD

**Issue by DanielHabenicht** [oozcitak/xmlbuilder2#82]
**Describe the bug**
Convert should recognise "escaped" characters and parse them correctly. 

**To Reproduce**
```
var xmlbuilder2 = require("xmlbuilder2")

const xmlBase = {
  xliff: {
    "@version": "1.2",
    file: {
      "@datatype": "plaintext",
      "@source-language": "en",
      body: {
      "@id": "test",
      source: "<this> test </this>"
      },
    },
  },
};

src = xmlbuilder2.convert(xmlBase, { prettyPrint: true })
console.log(src)
// "<?xml version=\"1.0\"?>\n<xliff version=\"1.2\">\n  <file … &lt;/this&gt;</source>\n    </body>\n  </file>\n</xliff>"

xmlbuilder2.convert(src, {format: "object"})
```
![image](https://user-images.githubusercontent.com/13590797/111848040-6b6e4880-890a-11eb-9182-35868396df90.png)

**Expected behaviour**
Convert does encode special characters like `<` or `>` as `&amp;lt;` and `&amp;gt;` But does not decode them if parsed again.

**Version:**
 - node.js: 15.12.0
 - xmlbuilder2 2.4.0

**Comment by DanielHabenicht** [comment]
Workaround: Use CDATA e.g.: 

```
var xmlbuilder2 = require("xmlbuilder2")

const xmlBase = {
  xliff: {
    "@version": "1.2",
    file: {
      "@datatype": "plaintext",
      "@source-language": "en",
      body: {
      "@id": "test",
      $: "<this> test </this>"
      },
    },
  },
};

src = xmlbuilder2.convert(xmlBase, { prettyPrint: true })
console.log(src)
// "<?xml version=\"1.0\"?>\n<xliff version=\"1.2\">\n  <file … &lt;/this&gt;</source>\n    </body>\n  </file>\n</xliff>"

xmlbuilder2.convert(src, {format: "object"})
```

**Comment by kernwig** [comment]
I ran into this too. Being able to parse back its own output is a basic test. This isn't just failing to decode XML entities, it's actually encoding them again (thus escaping `&apos;` to `&amp;apos;` instead of to `'`).

CDATA is not only unnecessary, it's impossible when you don't control the source.
