### ISSUE TITLE
@types/node is listed as dependency rather than a devDependency

### ISSUE THREAD

**Issue by fde31** [oozcitak/xmlbuilder2#84]
**Describe the bug**
Not necessarily a bug but I noticed that the `@types/node` package is listed as production dependency, adding additional bloat to the package. Maybe I missed something, but is it necessary or just an oversight?

**Expected behavior**
I expect xmlbuilder to only still `production` relevant dependencies when running `npm install --production`

**Version:**
 - xmlbuilder2 [2.4.0]

Happy to make a PR for this change but thought I'd check first if there is a specific reason it's not just a `devDependency`

Thanks

**Comment by campionfellin** [comment]
Any update here? This is a change I'd like to see as well

**Comment by campionfellin** [comment]
Would it be possible to use `*` as the node version instead of `14.6.2`?

**Comment by oozcitak** [comment]
> Would it be possible to use * as the node version instead of 14.6.2?

Can you describe why you require this?

**Comment by campionfellin** [comment]
@oozcitak would you be able to release a new version of `xmlbuilder2` please? :)

**Comment by campionfellin** [comment]
Yes, that's great :) Enjoy your trip! 😎
