### ISSUE TITLE
headless from xmlbuilder

### ISSUE THREAD

**Issue by diegogarciar** [oozcitak/xmlbuilder2#87]
**Is your feature request related to a problem? Please describe.**
I would like that the headless option from the original xmlbuilder be available xmlbuilder2

**Describe the solution you'd like**
Add ability to use {headless:true}  when creating the root element

**Comment by oozcitak** [comment]
It's already there: https://oozcitak.github.io/xmlbuilder2/serialization.html#xml-string-serializer
