### ISSUE TITLE
xmlns attribute doesn't appear on children if parent already has it

### ISSUE THREAD

**Issue by gbpaixao** [oozcitak/xmlbuilder2#93]
Hello,
I'm trying to use xmlbuilder2 to create a xml like this: 
```
<nfeP xmlns="website", version='2.0'>
  <nfe xmlns="website, version='2.0'" />
</nfeP>
```

The code I'm using to create the Object is: 
```
const obj = {
   nfeP: {
      '@': { xmlns: 'website', version: '2.0' }
      NFe: {
         '@': { xmlns: 'website',  version: '2.0' }   
      }
   }
}
```

But what I'm getting is:
```
<nfeP xmlns="website", version='2.0'><br>
  <nfe version='2.0' />
</nfeP>
```

I also noticed this happens with every children of "nfe". 

**Version:**
 - node.js: [12.17.0]
 - xmlbuilder2 [2.4.1]

**Comment by oozcitak** [comment]
As you probably now these two documents are canonically equivalent:
```xml
<nfeP xmlns="website" version="2.0">
  <nfe xmlns="website" version="2.0"/>
</nfeP>
```
```xml
<nfeP xmlns="website" version="2.0">
  <nfe version="2.0"/>
</nfeP>
```
In both cases the child `nfe` element would have the `namespaceURI` `website`.

`xmlbuilder2` chooses the second form when serializing the document; as the first representation is superfluous. Is there any reason you want this form?
