### ISSUE TITLE
How do you append a fragment/node?

### ISSUE THREAD

**Issue by totszwai** [oozcitak/xmlbuilder2#96]
Why is it that we must create a new node using `ele`? Can't we just create a `fragment` and **append** it to an existing node? If this is already supported, how do we do it?

I would like to create a fragment separately and then append them to an existing node, this should make the code cleaner by decoupling them from the parent node.

Example use case:
```
function generateDestinationLocation(destUrl) {
  const frag = fragment('destLocation');
  const dest = new URL(destUrl);
  frag.ele('protocol', {}, dest.protocol);
  frag.ele('host', {}, dest.host);
  frag.ele('port', {}, dest.port);
  frag.ele('path', {}, dest.pathname);
  return frag;
}

const test = create('test');
test.append(generateDestinationLocation(someUrl));
```

This helps if the XML document is large and complex by breaking down complex node into manageable function that creates their little fragment.

**Comment by oozcitak** [comment]
You can do that. The function to use is `import`. See: https://oozcitak.github.io/xmlbuilder2/node-creation-functions.html#import

**Comment by Extarys** [comment]
I know this is old, but maybe this should be said in the documentation about fragments.
