### ISSUE TITLE
How do we create a node with with syntax <?blah ?>

### ISSUE THREAD

**Issue by totszwai** [oozcitak/xmlbuilder2#97]
I am trying to generate an XML file that has the following structure:

```
<?xml version='1.0' encoding='UTF-8' ?>
<?charles serialisation-version='2.0' ?>
<map>
...
</map>
```

How could we create the second node such as `<?charles serialisation-version='2.0' ?>`?

**Comment by oozcitak** [comment]
That's a processing instruction node. See: https://oozcitak.github.io/xmlbuilder2/node-creation-functions.html#ins
